/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { LucideIcon } from 'lucide-react';
import React from 'react';
import { motion } from 'framer-motion';
import { Brain, Zap, Target, Scale } from 'lucide-react';

const AnalysisCard = ({
  icon: Icon,
  title,
  subtitle,
  children,
  delay,
  color,
}: {
  icon: LucideIcon;
  title: string;
  subtitle: string;
  children: React.ReactNode;
  delay: number;
  color: 'blue' | 'purple' | 'emerald' | 'amber';
}) => {
  const colorClasses = {
    blue: 'bg-blue-50 border-blue-200 text-blue-900',
    purple: 'bg-purple-50 border-purple-200 text-purple-900',
    emerald: 'bg-emerald-50 border-emerald-200 text-emerald-900',
    amber: 'bg-amber-50 border-amber-200 text-amber-900',
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: delay, duration: 0.5 }}
      className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden hover:shadow-md transition-shadow"
    >
      <div className={`p-4 border-b ${colorClasses[color].replace('text-', 'border-').split(' ')[2]}`}>
        <div className="flex items-center gap-3">
          <div className={`p-2 rounded-lg ${colorClasses[color].split(' ')[0]}`}>
            <Icon className={`w-5 h-5 ${colorClasses[color].split(' ')[2]}`} />
          </div>
          <div>
            <h4 className="font-semibold text-slate-900">{title}</h4>
            <p className="text-xs text-slate-500">{subtitle}</p>
          </div>
        </div>
      </div>
      <div className="p-4">{children}</div>
    </motion.div>
  );
};

const AnalysisGrid: React.FC = () => {
  return (
    <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
      {/* Distillation + RL */}
      <AnalysisCard
        icon={Brain}
        title="SFT Distillation"
        subtitle="Essential for reasoning effectiveness"
        delay={0.1}
        color="blue"
      >
        <div className="space-y-3">
          <p className="text-sm text-slate-600">
            Reasoning judges trained with both SFT distillation (from gold-standard reasoning traces) and GRPO achieve significantly better agreement with the gold-standard judge.
          </p>
          <div className="p-3 bg-blue-50 rounded-lg">
            <div className="flex justify-between text-sm mb-1">
              <span className="text-slate-600">Distillation + RL (Qwen3-4B)</span>
              <span className="font-semibold text-blue-700">85.94</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-slate-600">RL Only (Qwen3-4B)</span>
              <span className="font-semibold text-blue-700">85.10</span>
            </div>
          </div>
          <p className="text-xs text-slate-500">
            Access to gold-standard reasoning traces is critical for training effective reasoning judges.
          </p>
        </div>
      </AnalysisCard>

      {/* Rubrics */}
      <AnalysisCard
        icon={Target}
        title="Rubric Augmentation"
        subtitle="Not enough for non-reasoning judges"
        delay={0.2}
        color="purple"
      >
        <div className="space-y-3">
          <p className="text-sm text-slate-600">
            Providing instruction-specific rubrics generated by the gold-standard judge improves non-reasoning judge performance but doesn't prevent reward hacking.
          </p>
          <div className="p-3 bg-purple-50 rounded-lg">
            <div className="flex justify-between text-sm mb-1">
              <span className="text-slate-600">Fine-tuned w/o Rubrics</span>
              <span className="font-semibold text-purple-700">87.82</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-slate-600">Fine-tuned w/ Rubrics</span>
              <span className="font-semibold text-purple-700">89.72</span>
            </div>
          </div>
          <p className="text-xs text-slate-500">
            Rubrics help but cannot substitute for actual reasoning capability in the judge.
          </p>
        </div>
      </AnalysisCard>

      {/* Reasoning Effort */}
      <AnalysisCard
        icon={Zap}
        title="Reasoning Effort"
        subtitle="More computation = better policies"
        delay={0.3}
        color="emerald"
      >
        <div className="space-y-3">
          <p className="text-sm text-slate-600">
            The gold-standard judge's reasoning effort directly impacts the quality of trained reasoning judges and resulting policies.
          </p>
          <div className="p-3 bg-emerald-50 rounded-lg">
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-slate-600">Low Effort</span>
                <span className="font-semibold text-emerald-700">79.88</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-600">Medium Effort</span>
                <span className="font-semibold text-emerald-700">85.99</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-600">High Effort</span>
                <span className="font-semibold text-emerald-700">89.34</span>
              </div>
            </div>
          </div>
          <p className="text-xs text-slate-500">
            Higher reasoning effort (more tokens in thinking traces) leads to better judge agreement and stronger policies.
          </p>
        </div>
      </AnalysisCard>

      {/* Pairwise Comparison */}
      <AnalysisCard
        icon={Scale}
        title="Pairwise Judges"
        subtitle="Same pattern, higher cost"
        delay={0.4}
        color="amber"
      >
        <div className="space-y-3">
          <p className="text-sm text-slate-600">
            Pairwise comparison judges show the same advantage of reasoning over non-reasoning, but require ~6x more computation.
          </p>
          <div className="p-3 bg-amber-50 rounded-lg">
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-slate-600">Non-Reasoning (FT)</span>
                <span className="font-semibold text-amber-700">90.0%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-600">Reasoning (FT)</span>
                <span className="font-semibold text-amber-700">94.8%</span>
              </div>
            </div>
          </div>
          <p className="text-xs text-slate-500">
            Reasoning pairwise judges achieve ~90.8% win rate on Arena-Hard creative writing, outperforming many frontier models.
          </p>
        </div>
      </AnalysisCard>
    </div>
  );
};

export default AnalysisGrid;
