export interface PreLieStructure {
  name: string;
  description: string;
  condition: string;
  properties: string[];
  examples: string[];
}

export interface Section {
  id: string;
  title: string;
  content: string;
  is3D: boolean;
}

export interface Author {
  name: string;
  affiliation: string;
}

export const PAPER_INFO = {
  title: "Pre-Lie Structures for Semisimple Lie Algebras",
  authors: [
    { name: "Xerxes D. Arsiwalla", affiliation: "Wolfram Institute for Computational Foundations of Science, USA" },
    { name: "Fernando Olivie Méndez Méndez", affiliation: "University of Leeds, UK" }
  ],
  abstract: "We address the problem of admissibility of pre-Lie structures associated with a given Lie algebra, particularly, semisimple Lie algebras over ℂ. Among the five classes of nonassociative Lie-admissible algebras, left-symmetric algebras (LSAs) and right-symmetric algebras (RSAs), are known to be non-admissible by semisimple Lie algebras of finite dimension n ≥ 3. Here, we examine the remaining classes starting with those corresponding to the subgroup generated by permutations of order 2: (1 3). These appear in the literature as anti-flexible algebras (AFAs). We then prove that S₃-associative algebras are universal pre-Lie structures for any Lie algebra over ℂ, including semisimple ones.",
  keywords: ["Nonassociative Algebras", "Lie-Admissible Algebras", "Pre-Lie Structures", "Semisimple Lie Algebras"]
};

export const PRE_LIE_STRUCTURES: PreLieStructure[] = [
  {
    name: "Left-Symmetric Algebras (LSA)",
    description: "Also known as Vinberg algebras, these define flat torsion-free left-invariant affine structures.",
    condition: "(x, y, z) = (y, x, z)",
    properties: ["Lie-admissible", "Define flat torsion-free connections", "Opposite of RSA"],
    examples: ["Solvable Lie algebras admit LSAs"]
  },
  {
    name: "Right-Symmetric Algebras (RSA)",
    description: "The 'opposite algebras' of LSAs, sometimes called pre-Lie algebras.",
    condition: "(x, y, z) = (x, z, y)",
    properties: ["Lie-admissible", "Define flat torsion-free connections", "Opposite of LSA"],
    examples: ["Solvable Lie algebras admit RSAs"]
  },
  {
    name: "Anti-Flexible Algebras (AFA)",
    description: "Corresponding to permutations of order 2, also called Center-Symmetric Algebras.",
    condition: "(x, y, z) = (z, y, x)",
    properties: ["Lie-admissible", "Richer geometric structures than LSAs/RSAs", "Their own opposite algebra"],
    examples: ["Solvable Lie algebras admit AFAs", "𝔰𝔩(2,ℂ) admits an AFA"]
  },
  {
    name: "A₃-Associative Algebras",
    description: "Corresponding to the alternating group A₃ (even permutations).",
    condition: "(x, y, z) + (y, z, x) + (z, x, y) = 0",
    properties: ["Lie-admissible", "Satisfy first Bianchi identity", "Related to knot theory quandles"],
    examples: ["Cross-product algebra in 3D", "𝔰𝔲(2) admits A₃-associative structure"]
  },
  {
    name: "S₃-Associative Algebras",
    description: "Universal pre-Lie structures admitting the full S₃ group action on associators.",
    condition: "(x, y, z) + (y, z, x) + (z, x, y) = (y, x, z) + (x, z, y) + (z, y, x)",
    properties: ["Lie-admissible", "Subsume all other classes", "Universal for all Lie algebras"],
    examples: ["Every Lie algebra over ℂ admits S₃-associative structure"]
  }
];

export const SECTION_ORDER = [
  { id: 'hero', title: 'Overview', is3D: true },
  { id: 'problem', title: 'The Problem', is3D: false },
  { id: 'structures', title: 'Pre-Lie Structures', is3D: false },
  { id: 'afas', title: 'Anti-Flexible Algebras', is3D: true },
  { id: 'results', title: 'Key Results', is3D: false },
  { id: 'authors', title: 'Authors', is3D: false }
];
